import {POINT_KEYS,validateCourse,fitCourseArt,safeURL,loadCourseData} from './model.mjs';
import {renderHazardLayer,renderPlayerLandingLayer,hasHazardLayer,hazardLegend} from './overlay.mjs';
const cssURL=new URL('./course-view.css',import.meta.url).href;
const el=(tag,props={},...children)=>{const n=document.createElement(tag);for(const [k,v]of Object.entries(props)){if(k==='text')n.textContent=v;else if(k.startsWith('on'))n.addEventListener(k.slice(2),v);else n.setAttribute(k,v)}for(const c of children)n.append(c);return n};
export class CourseView extends HTMLElement {
 #course=null;#assetBase=null;#point=null;#playerOverlay=null;#zoom=1;#hazards=true;#snapshot=null;#observers=[];#generation=0;#loadSequence=0;#abort=null;#modal=null;#status=null;#dialog=null;
 constructor(){super();this.attachShadow({mode:'open'})}
 connectedCallback(){this.#render()}
 disconnectedCallback(){this.#cleanup();this.#abort?.abort();this.#loadSequence++}
 #cleanup(){for(const o of this.#observers)o.disconnect();this.#observers=[];if(this.#dialog?.open)this.#dialog.close();this.#dialog=null}
 get assetBase(){return this.#assetBase??document.baseURI}
 set assetBase(value){this.#assetBase=safeURL(value,document.baseURI);this.#render()}
 get playerOverlay(){return this.#playerOverlay?structuredClone(this.#playerOverlay):null}
 set playerOverlay(value){this.#playerOverlay=value?structuredClone(value):null;this.#render()}
 get course(){return this.#course?structuredClone(this.#course):null}
 set course(value){this.setCourse(value)}
 get state(){return Object.freeze({courseId:this.#course?.courseId??null,view:this.#point?'point':'overview',point:this.#point,zoom:this.#zoom,showHazards:this.#hazards,dialogOpen:!!this.#dialog?.open})}
 #emit(name,detail){this.dispatchEvent(new CustomEvent(name,{detail,bubbles:true,composed:true}))}
 setCourse(value){this.#abort?.abort();this.#loadSequence++;const errors=validateCourse(value);if(errors.length){this.#emit('courseview-error',{code:'invalid-course',message:errors.join(', ')});throw new TypeError(errors.join(', '))}this.#course=structuredClone(value);this.#point=null;this.#zoom=1;this.#snapshot=null;this.#render();this.#emit('courseview-change',this.state)}
 async load(url,{courseId,expectedRelease}={}){
 const seq=++this.#loadSequence;this.#abort?.abort();this.#abort=new AbortController();
 try{const resolved=safeURL(url,document.baseURI);const data=await loadCourseData(resolved,{signal:this.#abort.signal,expectedRelease});if(seq!==this.#loadSequence)return null;const c=courseId?data.courses.find(c=>c.courseId===courseId):data.courses[0];if(!c)throw Error('Course ID not found');this.#assetBase=safeURL(data.assetBase??'../',resolved);this.setCourse(c);return data}
 catch(e){if(e.name==='AbortError'||seq!==this.#loadSequence)return null;this.#emit('courseview-error',{code:'load-failed',message:e.message});throw e}
 }
 selectPoint(key){if(!this.#course||!POINT_KEYS.includes(key))throw new TypeError('Unknown point');if(!this.#point){const s=this.shadowRoot.querySelector('.stage');this.#snapshot={zoom:this.#zoom,left:s?.scrollLeft??0,top:s?.scrollTop??0}}this.#point=key;this.#render();this.#emit('courseview-change',this.state);this.shadowRoot.querySelector('[data-key="'+key+'"]')?.focus()}
 showOverview(){const previous=this.#point;this.#point=null;if(this.#snapshot)this.#zoom=this.#snapshot.zoom;this.#render();const s=this.shadowRoot.querySelector('.stage');if(s&&this.#snapshot){s._fit();s.scrollLeft=this.#snapshot.left;s.scrollTop=this.#snapshot.top}this.#snapshot=null;this.#emit('courseview-change',this.state);this.shadowRoot.querySelector(previous?'[data-key="'+previous+'"]':'[data-key="overview"]')?.focus()}
 setZoom(value){if(!Number.isFinite(value))throw new TypeError('Zoom must be finite');this.#zoom=Math.max(1,Math.min(3,value));this.#render();this.#emit('courseview-change',this.state)}
 setHazards(value){this.#hazards=Boolean(value);this.#render();this.#emit('courseview-change',this.state)}
 closeDialog(){this.#dialog?.close()}
 openDialog(){if(!this.#course||this.#dialog?.open)return;const opener=this.shadowRoot.activeElement,asset=this.#asset();const dialog=el('dialog',{'aria-label':asset.alt});this.#dialog=dialog;
 const close=el('button',{text:'閉じる',onclick:()=>dialog.close()});dialog.append(el('div',{class:'dialog-head'},el('h2',{text:this.#point?this.#course.points[this.#point].label:'全体図'}),close));
 let z=1;const value=el('span',{class:'zoom-label',text:'100%'});const minus=el('button',{text:'縮小','aria-label':'拡大画像を縮小',onclick:()=>adjust(z-.25)}),plus=el('button',{text:'拡大','aria-label':'拡大画像を拡大',onclick:()=>adjust(z+.25)}),reset=el('button',{text:'全体表示',onclick:()=>adjust(1)});dialog.append(el('div',{class:'controls'},minus,value,plus,reset));const stage=this.#makeStage(asset,!this.#point,()=>z,'modal-stage');dialog.append(stage,this.#credit());this.shadowRoot.append(dialog);
 const adjust=next=>{z=Math.max(1,Math.min(3,next));value.textContent=Math.round(z*100)+'%';minus.disabled=z===1;plus.disabled=z===3;stage._fit()};
 dialog.addEventListener('close',()=>{stage._destroy?.();dialog.remove();if(this.#dialog===dialog)this.#dialog=null;opener?.focus();this.#emit('courseview-change',this.state)},{once:true});dialog.showModal();adjust(1);close.focus();this.#emit('courseview-change',this.state)
 }
 #asset(){return this.#point?{...this.#course.scenes[this.#point],alt:`${this.#course.points[this.#point].label}のコース写真`}:{src:this.#course.image,width:this.#course.art.width,height:this.#course.art.height,alt:`${this.#course.courseName} ${this.#course.hole}番のコース図`}}
 #credit(){const p=el('p',{class:'credit'});if(this.#course?.sourceCredit){const c=this.#course.sourceCredit;p.append(el('a',{href:safeURL(c.url),target:'_blank',rel:'noopener noreferrer',text:c.text}))}if(this.#course?.provenance)p.append(' ',el('a',{href:safeURL(this.#course.provenance.url),target:'_blank',rel:'noopener noreferrer',text:'コース情報の出典'}));return p}
 #makeStage(asset,overview,zoom,extra=''){
 const generation=this.#generation,stage=el('div',{'aria-busy':'true','class':'stage '+extra,tabindex:'0','aria-label':'画像。拡大時は矢印キーまたはスクロールで移動'}),canvas=el('div',{class:'canvas'}),img=el('img',{class:'art',alt:asset.alt,draggable:'false',width:asset.width,height:asset.height}),error=el('p',{class:'error',text:'画像を読み込めませんでした。通信とアセットの配置を確認してください。','role':'status',hidden:''});const retry=el('button',{text:'再読込',onclick:()=>{error.hidden=true;canvas.hidden=false;img.src=safeURL(asset.src,this.assetBase)}});error.append(retry);const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('class','overlay');svg.setAttribute('viewBox',`0 0 ${asset.width} ${asset.height}`);svg.setAttribute('aria-hidden','true');if(overview){svg.innerHTML=[this.#hazards&&hasHazardLayer(this.#course)?renderHazardLayer(this.#course):'',this.#playerOverlay?renderPlayerLandingLayer(this.#course,this.#playerOverlay):''].join('')}svg.toggleAttribute('hidden',!overview||(!this.#playerOverlay&&(!this.#hazards||!hasHazardLayer(this.#course))));canvas.append(img,svg);stage.append(canvas,error);
 const fit=()=>{if(!stage.isConnected)return;const oldX=stage.scrollLeft+stage.clientWidth/2,oldY=stage.scrollTop+stage.clientHeight/2,oldW=parseFloat(canvas.style.width)||0,oldH=parseFloat(canvas.style.height)||0;const d=fitCourseArt(stage.clientWidth||320,stage.clientHeight||480,zoom(),asset.width,asset.height);Object.assign(canvas.style,{width:d.canvasWidth+'px',height:d.canvasHeight+'px'});for(const n of[img,svg])Object.assign(n.style,{width:d.imageWidth+'px',height:d.imageHeight+'px',left:d.left+'px',top:d.top+'px'});svg.style.fontSize=Math.max(40,14/d.scale)+'px';stage.scrollLeft=oldW?oldX/oldW*d.canvasWidth-stage.clientWidth/2:d.scrollLeft;stage.scrollTop=oldH?oldY/oldH*d.canvasHeight-stage.clientHeight/2:d.scrollTop};stage._fit=fit;
 img.addEventListener('error',()=>{if(!this.isConnected||!stage.isConnected||generation!==this.#generation)return;stage.setAttribute('aria-busy','false');canvas.hidden=true;error.hidden=false;this.#emit('courseview-error',{code:'image-failed',courseId:this.#course.courseId,point:this.#point,src:asset.src})});img.addEventListener('load',()=>{if(!this.isConnected||!stage.isConnected||generation!==this.#generation)return;stage.setAttribute('aria-busy','false');canvas.hidden=false;error.hidden=true;fit();this.#emit('courseview-ready',{courseId:this.#course.courseId,point:this.#point,src:asset.src})});img.src=safeURL(asset.src,this.assetBase);
 let drag=null;stage.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse'||e.button!==0||e.target.closest('button'))return;drag={x:e.clientX,y:e.clientY,left:stage.scrollLeft,top:stage.scrollTop};stage.setPointerCapture(e.pointerId);e.preventDefault();stage.focus()});stage.addEventListener('pointermove',e=>{if(drag){stage.scrollLeft=drag.left-e.clientX+drag.x;stage.scrollTop=drag.top-e.clientY+drag.y}});for(const event of ['pointerup','pointercancel','lostpointercapture'])stage.addEventListener(event,()=>drag=null);
 if(typeof ResizeObserver!=='undefined'){const o=new ResizeObserver(fit);o.observe(stage);this.#observers.push(o);stage._destroy=()=>{o.disconnect();this.#observers=this.#observers.filter(x=>x!==o)}}queueMicrotask(fit);return stage;
 }
 #render(){if(!this.isConnected)return;const focusLabel=this.shadowRoot.activeElement?.getAttribute('aria-label');this.#cleanup();this.#generation++;this.shadowRoot.replaceChildren(el('link',{rel:'stylesheet',href:cssURL}));const shell=el('section',{class:'shell','aria-label':'コース図'});this.shadowRoot.append(shell);if(!this.#course){shell.append(el('p',{text:'コースデータを設定してください。',role:'status'}));return}const c=this.#course;shell.append(el('h2',{text:`${c.courseName} ${c.hole}番 / コース図`}));
 const controls=el('div',{class:'controls'});controls.append(el('button',{text:'全体図','data-key':'overview','aria-pressed':String(!this.#point),onclick:()=>this.showOverview()}),el('button',{text:'大きく表示',onclick:()=>this.openDialog()}));if(!this.#point){const minus=el('button',{text:'−','aria-label':'縮小',onclick:()=>this.setZoom(this.#zoom-.25)}),plus=el('button',{text:'＋','aria-label':'拡大',onclick:()=>this.setZoom(this.#zoom+.25)});minus.disabled=this.#zoom===1;plus.disabled=this.#zoom===3;controls.append(minus,el('span',{class:'zoom-label',text:Math.round(this.#zoom*100)+'%'}),plus,el('button',{text:'全体に合わせる',onclick:()=>this.setZoom(1)}));const check=el('input',{type:'checkbox','aria-label':'ハザードの注意表示'});check.checked=this.#hazards;check.disabled=!hasHazardLayer(c);check.addEventListener('change',()=>this.setHazards(check.checked));controls.append(el('label',{},check,' 注意表示'))}shell.append(controls);
 const points=el('div',{class:'points','aria-label':'要点ビュー'});for(const k of POINT_KEYS){const a=c.scenes[k],img=el('img',{src:safeURL(a.src,this.assetBase),alt:'',loading:'lazy',width:a.width,height:a.height});img.addEventListener('error',()=>img.hidden=true);points.append(el('button',{'data-key':k,'aria-pressed':String(this.#point===k),onclick:()=>this.selectPoint(k)},img,el('span',{text:c.points[k].label})))}shell.append(points,el('p',{class:'status',role:'status','aria-live':'polite',text:this.#point?c.points[this.#point].label:'コース図'}));
 const stage=this.#makeStage(this.#asset(),!this.#point,()=>this.#point?1:this.#zoom);shell.append(stage);if(!this.#point&&this.#hazards&&hasHazardLayer(c)){const legend=el('div',{class:'legend'});legend.innerHTML=hazardLegend(c);shell.append(legend)}shell.append(this.#credit());if(focusLabel){for(const node of this.shadowRoot.querySelectorAll('[aria-label]'))if(node.getAttribute('aria-label')===focusLabel&&node instanceof HTMLElement){node.focus();break}}
 }
}
if(!customElements.get('course-view'))customElements.define('course-view',CourseView);
